services:
  - type: web
    name: ev-fleet-management
    env: python
    buildCommand: |
      export PYTHON_CONFIGURE_OPTS="--enable-shared"
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ev_fleet_management.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEBUG
        value: True
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DISABLE_COLLECTSTATIC
        value: 0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_URL
        fromDatabase:
          name: ev_fleet_db
          property: connectionString
      - key: PIP_NO_BINARY
        value: ""
    autoDeploy: true
    disk:
      name: ev-data
      mountPath: /opt/render/project/src/Datasets
      sizeGB: 1 

databases:
  - name: ev_fleet_db
    plan: free
    ipAllowList: [] 